#!/usr/bin/env python3
"""
Human AI: Native Worker Agent - v2.1
Directly implements tasks using OpenRouter and local system tools.
"""

import asyncio
import os
import json
import requests
from typing import Dict, Any, Optional
from dotenv import load_dotenv

load_dotenv('/home/ubuntu/human-ai/.env')

class NativeWorker:
    def __init__(self):
        self.api_key = os.getenv("OPENROUTER_API_KEY")
        # Use a highly stable free model
        self.model = "google/gemma-4-31b-it:free" 
        self.working_dir = os.getenv("WORK_DIR", "/home/ubuntu/human-ai")

    async def execute_task(self, task_prompt: str) -> Dict[str, Any]:
        print(f"🛠️ Native Worker executing: {task_prompt[:100]}...")
        
        # Clean the prompt to remove error messages from the brain
        clean_prompt = task_prompt.replace("Brain Query Error:", "").strip()
        
        system_prompt = "You are a senior Python developer. Provide ONLY the raw Python code. No markdown, no backticks, no explanations. Just the code."
        
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://openclaw.ai",
            "X-Title": "Human-AI Swarm"
        }
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": clean_prompt}
            ]
        }
        
        try:
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                None, 
                lambda: requests.post("https://openrouter.ai/api/v1/chat/completions", headers=headers, json=payload, timeout=60)
            )
            
            if response.status_code != 200:
                print(f"❌ API Error {response.status_code}: {response.text}")
                return {"status": "error", "error": response.text}

            code = response.json()['choices'][0]['message']['content'].strip()
            
            # Robust cleaning of markdown
            if "```" in code:
                import re
                match = re.search(r"```(?:python)?\s*(.*?)\s*```", code, re.DOTALL)
                if match:
                    code = match.group(1)
            
            print("✅ Code generated by Native Worker.")
            return {
                "status": "success",
                "result": code,
                "output": code
            }
        except Exception as e:
            print(f"❌ Native Worker error: {e}")
            return {"status": "error", "error": str(e)}

async def main():
    worker = NativeWorker()
    result = await worker.execute_task("Create a simple Python script that prints 'Hello from Native Worker!'")
    print(f"Result: {result}")

if __name__ == "__main__":
    asyncio.run(main())
