#!/usr/bin/env python3
"""
Human AI: Native Worker Agent - v3.0 (Browser-First Compliant)
Implements tasks by delegating to the DeepSeek Browser Agent,
ensuring all LLM interactions run through the browser (Playwright).
"""

import asyncio
import os
import json
import sys
from typing import Dict, Any, Optional
from pathlib import Path
from dotenv import load_dotenv

# Add project root to path to import local agents
sys.path.append('/home/ubuntu/human-ai/core/agents')
from researcher.deepseek_browser_agent import DeepSeekBrowserAgent

load_dotenv('/home/ubuntu/human-ai/.env')

class NativeWorker:
    def __init__(self):
        self.working_dir = os.getenv("WORK_DIR", "/home/ubuntu/human-ai")
        # We will create a browser instance on-demand for each task
        # to ensure isolation and avoid state conflicts.

    async def execute_task(self, task_prompt: str) -> Dict[str, Any]:
        print(f"🛠️ Native Worker (Browser-First) executing: {task_prompt[:100]}...")
        
        # Clean the prompt to remove error messages from the brain
        clean_prompt = task_prompt.replace("Brain Query Error:", "").strip()
        
        # System prompt to guide the LLM to produce clean, executable code
        system_prompt = "You are a senior Python developer. Your task is to write Python code to fulfill the user's request. Provide ONLY the raw Python code. No markdown, no backticks, no explanations. Just the code that can be directly executed."
        
        # The final prompt for the LLM
        final_prompt = f"{system_prompt}\n\nUser Request: {clean_prompt}"
        
        browser_agent = None
        try:
            # Instantiate and use the browser agent
            browser_agent = DeepSeekBrowserAgent()
            await browser_agent.start_browser()
            
            # Ensure we are logged in (this will use cookies if available)
            session_path = os.getenv("SESSION_PATH", "/home/ubuntu/human-ai/session/state.json")
            if not os.path.exists(session_path):
                await browser_agent.login()
            
            # Get the response from the LLM via the browser
            code = await browser_agent.prompt(final_prompt)
            
            # Robust cleaning of markdown (just in case)
            if "```" in code:
                import re
                match = re.search(r"```(?:python)?\s*(.*?)\s*```", code, re.DOTALL)
                if match:
                    code = match.group(1)
            
            print("✅ Code generated by Native Worker via Browser.")
            return {
                "status": "success",
                "result": code.strip(),
                "output": code.strip()
            }
            
        except Exception as e:
            print(f"❌ Native Worker error: {e}")
            return {"status": "error", "error": str(e)}
        finally:
            # Always clean up the browser resources
            if browser_agent:
                await browser_agent.close()

async def main():
    worker = NativeWorker()
    result = await worker.execute_task("Create a simple Python script that prints 'Hello from Native Worker!'")
    print(f"Result: {result}")

if __name__ == "__main__":
    asyncio.run(main())
